[api]
port = 55321

[db]
port = 55322
shadow_port = 55320

[studio]
port = 55323

[local_smtp]
port = 55324
smtp_port = 55325
pop3_port = 55326

[analytics]
port = 55327

[db.pooler]
port = 55329

[functions.outlook-calendar]
verify_jwt = false

[functions.whatsapp-summary]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-processor]
verify_jwt = false
