import assert from "node:assert/strict";
await import("../conversation-completeness.js");
const engine=globalThis.CriareConversationCompleteness;
const audio=(id,status={},extra={})=>({message_id:id,type:"Áudio",text:"[10:00, 01/07/2026] Cliente: [Áudio sem transcrição]",...status,...extra});
const text=(id="T1")=>({message_id:id,type:"Texto",text:"[09:00, 01/07/2026] Cliente: Olá"});
const record=(entries,extra={})=>({id:"lead",whatsapp_message_entries:entries,whatsapp_capture_complete:true,whatsapp_transcript_updated_at:"2026-07-01T13:00:00Z",...extra});

assert.equal(engine.calculate(record([], {whatsapp_transcript_updated_at:null})).conversation_status,"not_captured");
assert.equal(engine.calculate({whatsapp_transcript:"[10:00, 01/07/2026] Cliente: [Áudio sem transcrição]",whatsapp_sync_message_count:1,whatsapp_capture_complete:true}).pending_audio_count,1);
assert.equal(engine.calculate(record([text()])).conversation_completeness_status,"complete");
assert.equal(engine.calculate(record([audio("A",{}, {transcript:"texto"})])).transcribed_audio_count,1);
assert.equal(engine.calculate(record([audio("A")])).pending_audio_count,1);
assert.equal(engine.calculate(record([audio("A"),audio("B")])).pending_audio_count,2);
assert.equal(engine.calculate(record([audio("A",{media_status:"media_unavailable"})])).unavailable_audio_count,1);
assert.equal(engine.calculate(record([audio("A",{transcription_status:"transcription_error"})])).failed_transcription_count,1);
assert.equal(engine.calculate(record([audio("wa:A"),audio("A",{}, {transcript:"feito"})])).total_audio_messages,1);
assert.equal(engine.calculate(record([audio("A",{}, {transcript:"feito"})],{whatsapp_analysis_updated_at:"2026-06-01T00:00:00Z",whatsapp_analysis_status:"current"})).analysis_status,"stale");
assert.equal(engine.matchesFilter(engine.calculate(record([audio("A")])),"pending"),true);
assert.equal(engine.matchesFilter(engine.calculate(record([text()],{whatsapp_capture_complete:false})),"incomplete"),true);
const queue=engine.buildSyncQueue([{id:"ok"},{id:"bad"},{id:"dup"}],item=>item.id==="ok"?{ready:true,code:"ready",normalized:"+5519999999999"}:item.id==="dup"?{ready:false,code:"phone_duplicate"}:{ready:false,code:"phone_invalid"});
assert.deepEqual(queue.map(item=>item.status),["waiting","phone_invalid","phone_duplicate"]);
assert.equal(engine.audioStatus(audio("",{})),"verification_required");
assert.equal(engine.audioStatus(audio("A",{}, {audioMeta:{fileObtained:true}})),"pending_import");
assert.equal(engine.calculate(record([text()],{whatsapp_sync_error:"rede"})).conversation_status,"sync_error");
assert.equal(engine.calculate(record([text()]),{identity_status:"phone_duplicate"}).conversation_status,"verification_required");
assert.equal(engine.sortRows([{summary:engine.calculate(record([text()]))},{summary:engine.calculate(record([audio("A")],{whatsapp_analysis_status:"never"}))}])[0].summary.pending_audio_count,1);
assert.equal(engine.calculate(record([audio("A",{media_status:"media_unavailable"})])).conversation_completeness_status,"unavailable_audio");
assert.equal(engine.calculate(record([audio("A",{transcription_status:"failed"})])).conversation_completeness_status,"pending_audio");
const readyAudio=(id,duration)=>audio(id,{}, {sender:"Cliente",direction:"incoming",date:"01/07/2026",message_time:"10:00",duration_seconds:duration,duration_valid:true});
const fivePending=engine.calculate(record([readyAudio("A",10),readyAudio("B",11),readyAudio("C",12),readyAudio("D",13),audio("E",{}, {sender:"Cliente",direction:"incoming",date:"01/07/2026",message_time:"10:01",duration_valid:false})]));
assert.equal(fivePending.pending_audio_count,5);assert.equal(fivePending.ready_for_import_count,4);assert.equal(fivePending.metadata_pending_audio_count,1);assert.match(fivePending.completeness_reasons.join(" "),/aguardando atualização de metadados/);
assert.equal(engine.calculate(record([text()]),{identity_status:"conversation_linked"}).conversation_completeness_status,"complete");
assert.equal(engine.matchesSearch({first_name:"Crislaine",last_name:"Silvia"},["+5519999999999","(19) 99999-9999"],"crislaine"),true);
assert.equal(engine.matchesSearch({first_name:"Crislaine"},["+5519999999999"],"+5519"),true);
assert.equal(engine.matchesSearch({first_name:"Crislaine"},["+5519999999999"],"Luiza"),false);
assert.equal(engine.version,"2.5.1");
console.log("conversation completeness tests: ok");
