import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

await import("../batch-analysis.js");
await import("../management-activity-report.js");
const report=globalThis.CriareManagementActivityReport;
const ownerA="00000000-0000-4000-8000-000000000101",ownerB="00000000-0000-4000-8000-000000000102";
const profiles=[{id:ownerA,display_name:"Mariana"},{id:ownerB,display_name:"Micaely"}];
const message=(id,timestamp,direction,text)=>({message_id:id,timestamp,direction,type:"Texto",text});
const records=[
  {id:"00000000-0000-4000-8000-000000000201",first_name:"Cliente",last_name:"Um",pipeline:"lead",stage:"Negociação",owner_id:ownerA,whatsapp_message_entries:[message("MSG-OLD","2026-08-01T12:00:00.000Z","incoming","Fora do período"),message("MSG-1","2026-08-10T12:00:00.000Z","incoming","Pode enviar o orçamento?"),message("MSG-2","2026-08-10T13:00:00.000Z","outgoing","A loja enviará amanhã.")]},
  {id:"00000000-0000-4000-8000-000000000202",first_name:"Parceiro",record_type:"specifier",owner_id:ownerB,whatsapp_message_entries:[message("MSG-3","2026-08-11T12:00:00.000Z","outgoing","Vamos alinhar a indicação.")]},
  {id:"00000000-0000-4000-8000-000000000203",first_name:"Sem atividade",pipeline:"closed",owner_id:ownerA,whatsapp_message_entries:[message("MSG-4","2026-07-01T12:00:00.000Z","incoming","Antiga")]}
];
async function snapshot(options={}){return report.buildSnapshot({records,profiles,workspaceId:"00000000-0000-4000-8000-000000000001",periodStart:"2026-08-10",periodEnd:"2026-08-11",now:"2026-08-12T12:00:00.000Z",...options});}
function validResult(value){return {schema_version:report.outputSchemaVersion,prompt_version:report.promptVersion,report_id:value.report_id,snapshot_hash:value.snapshot_hash,generated_at:"2026-08-12T13:00:00.000Z",analysis_model:"ChatGPT",executive_summary:"A equipe tratou de orçamento e relacionamento.",highlights:["A loja prometeu retorno."],manager_attention:[{contact_id:records[0].id,responsible_id:ownerA,reason:"Há uma entrega prometida.",evidence_message_ids:["MSG-2"]}],seller_summaries:[{responsible_id:ownerA,summary:"Carteira com negociação ativa.",contacts_handled:[records[0].id],alignments:["Orçamento"],company_commitments:["Enviar amanhã"],open_loops:["Confirmar envio"],coaching_observations:["Acompanhar o prazo"]},{responsible_id:ownerB,summary:"Contato com parceiro.",contacts_handled:[records[1].id],alignments:["Indicação"],company_commitments:[],open_loops:[],coaching_observations:[]}],contact_summaries:[{contact_id:records[0].id,responsible_ids:[ownerA],interaction_summary:"Cliente pediu orçamento e a loja prometeu enviá-lo.",topics:["Orçamento"],alignments:[],promises:[{promised_by:"company",description:"Enviar orçamento amanhã",due_at:null,evidence_message_ids:["MSG-2"]}],unanswered_questions:[],next_steps:["Confirmar envio"],evidence_message_ids:["MSG-1","MSG-2"]},{contact_id:records[1].id,responsible_ids:[ownerB],interaction_summary:"A loja propôs alinhamento de indicação.",topics:["Parceria"],alignments:["Alinhar indicação"],promises:[],unanswered_questions:[],next_steps:[],evidence_message_ids:["MSG-3"]}],coverage:{reviewed_contact_ids:[records[0].id,records[1].id]}};}

test("pacote gerencial usa somente mensagens do período",async()=>{const value=await snapshot();assert.equal(value.contacts.length,2);assert.deepEqual(value.contacts[0].messages.map(item=>item.message_id),["MSG-1","MSG-2"]);assert.equal(JSON.stringify(value).includes("Fora do período"),false);assert.deepEqual(value.source_summary,{contact_count:2,message_count:3,incoming_count:1,outgoing_count:2,incomplete_contact_count:0});});
test("filtro de responsável e tipo limita a carteira sem inferir autoria",async()=>{const value=await snapshot({selectedOwnerIds:[ownerA],entityTypes:["lead"]});assert.equal(value.contacts.length,1);assert.deepEqual(value.contacts[0].responsible_ids,[ownerA]);assert.match(value.attribution_notice,/não comprova quem digitou/);assert.equal(value.contacts[0].messages[1].direction,"outgoing");});
test("pacote contém instruções, schema e nome próprio do fluxo",async()=>{const value=await snapshot(),files=report.packageFiles(value),zip=globalThis.CriareBatchAnalysis.zipFiles(files);assert.deepEqual(Object.keys(files),["management_activity_input.json","management_activity_instructions.md","management_activity_output_schema.json","README.txt"]);assert.match(report.inputFilename(value.report_id),/^05-ENVIAR-AO-GPT_RELATORIO-GERENCIAL_/);assert.match(value.expected_output_filename,/^06-IMPORTAR-NO-CRM_RELATORIO-GERENCIAL_/);assert.match(files["management_activity_instructions.md"],/não afirme qual pessoa digitou/i);assert(zip.length>100);});
test("resultado válido exige cobertura e evidências do mesmo contato",async()=>{const value=await snapshot(),payload=validResult(value);assert.equal(report.validateResult(payload,value).valid,true);payload.contact_summaries[0].promises[0].evidence_message_ids=["MSG-3"];assert.match(report.validateResult(payload,value).errors.join(" "),/não pertence ao contato/);});
test("resultado incompleto, ID falso e hash divergente são bloqueados",async()=>{const value=await snapshot(),payload=validResult(value);payload.coverage.reviewed_contact_ids=[records[0].id];assert.match(report.validateResult(payload,value).errors.join(" "),/Cobertura incompleta/);payload.coverage.reviewed_contact_ids=[records[0].id,records[1].id];payload.manager_attention[0].contact_id="00000000-0000-4000-8000-999999999999";assert.match(report.validateResult(payload,value).errors.join(" "),/contato inexistente/);payload.manager_attention=[];payload.snapshot_hash="errado";assert.match(report.validateResult(payload,value).errors.join(" "),/não corresponde/);});
test("interface oferece período, responsáveis, exportação, importação e histórico",async()=>{const ui=await readFile(new URL("../management-activity-report-ui.js",import.meta.url),"utf8"),app=await readFile(new URL("../index.html",import.meta.url),"utf8");assert.match(ui,/Relatório gerencial das conversas/);assert.match(ui,/managementActivityStart/);assert.match(ui,/data-activity-owner/);assert.match(ui,/Baixar relatório para o GPT/);assert.match(ui,/Selecionar resultado do GPT/);assert.match(ui,/Relatórios anteriores/);assert.match(app,/management-activity-report\.js\?v=1\.0\.0/);assert.match(app,/management-activity-report-ui\.js\?v=1\.0\.0/);});
test("migração restringe relatórios ao administrador e não duplica mensagens",async()=>{const sql=await readFile(new URL("../supabase/migrations/20260812123000_management_activity_reports.sql",import.meta.url),"utf8");assert.match(sql,/crm_is_workspace_admin\(workspace_id\)/);assert.match(sql,/result_payload jsonb/);assert.doesNotMatch(sql,/message_text|messages jsonb|delete from/i);});
